#!/usr/bin/env python3

import glob, os
from subprocess import call

def dot2jpeg():
    os.chdir('AST/')
    # Pour tout les fichiers DOT
    for file in glob.glob('*.dot'):
        print("{0}.dot --> {0}.jpeg".format(file.split(".")[0]))
        call(['dot', '-Tjpeg', file, '-o', file.split('.')[0] + '.jpeg'])

if __name__ == '__main__':
    dot2jpeg()
